### ISSUE TITLE
Automatically pass in SEO to views

### ISSUE THREAD

**Issue by djam90** [helori/laravel-seo#1]
It would be great if the data could be automatically passed into the view instead of having to do it for each view. 

This could be a `view()->share()` in the base controller, or a service injected into the master template.

**Comment by helori** [comment]
Hi, (and sorry for the late answer)

The package has been updated so you can add all SEO info directly from your controller.
This is especially useful with dynamic routes where SEO data come from database specific items. 
The old package version was good only for static routes.

If you need to share some SEO data between views, you can specify it in your controller's constructor. 
I have put an example in the readme file.

Hope this helps!
Thanks
