### ISSUE TITLE
How to create dynamic config for route of products

### ISSUE THREAD

**Issue by blenderdeluxe** [helori/laravel-seo#2]
Hi!, I using your package in routes statics, but I dont understand how to use your package in a specific dynamic route, for example show-product, where I want get and set SEO for dyanmic products.

Thanks!, good job!

**Comment by helori** [comment]
Hi, sorry for the late answer !

I have updated the package to address this specific issue.
Things have changed a lot though... the config file does not exists anymore and all SEO info must be added directly from the controller. You can check the readme file for more details.

Hope this helps!
